/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingestion': typeof IngestionRoute
  '/review': typeof ReviewRoute
  '/traceability': typeof TraceabilityRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingestion': typeof IngestionRoute
  '/review': typeof ReviewRoute
  '/traceability': typeof TraceabilityRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingestion': typeof IngestionRoute
  '/review': typeof ReviewRoute
  '/traceability': typeof TraceabilityRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ingestion' | '/review' | '/traceability' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingestion' | '/review' | '/traceability' | '/upload'
  id: '__root__' | '/' | '/ingestion' | '/review' | '/traceability' | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngestionRoute: typeof IngestionRoute
  ReviewRoute: typeof ReviewRoute
  TraceabilityRoute: typeof TraceabilityRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngestionRoute: IngestionRoute,
  ReviewRoute: ReviewRoute,
  TraceabilityRoute: TraceabilityRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
